spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/mybatis_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: qwer1234

mybatis:
  type-aliases-package: com.example.AutoSys.domain
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
